<?php

namespace Proxies\__CG__\Sylius\Bundle\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Taxonomy extends \Sylius\Bundle\CoreBundle\Entity\Taxonomy implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getTaxonsForColecciones()
    {
        $this->__load();
        return parent::getTaxonsForColecciones();
    }

    public function getTaxonsForMayoristas()
    {
        $this->__load();
        return parent::getTaxonsForMayoristas();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getRoot()
    {
        $this->__load();
        return parent::getRoot();
    }

    public function setRoot(\Sylius\Bundle\TaxonomiesBundle\Model\TaxonInterface $root)
    {
        $this->__load();
        return parent::setRoot($root);
    }

    public function getTaxons()
    {
        $this->__load();
        return parent::getTaxons();
    }

    public function getTaxonsAsList()
    {
        $this->__load();
        return parent::getTaxonsAsList();
    }

    public function hasTaxon(\Sylius\Bundle\TaxonomiesBundle\Model\TaxonInterface $taxon)
    {
        $this->__load();
        return parent::hasTaxon($taxon);
    }

    public function addTaxon(\Sylius\Bundle\TaxonomiesBundle\Model\TaxonInterface $taxon)
    {
        $this->__load();
        return parent::addTaxon($taxon);
    }

    public function removeTaxon(\Sylius\Bundle\TaxonomiesBundle\Model\TaxonInterface $taxon)
    {
        $this->__load();
        return parent::removeTaxon($taxon);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'id', 'root');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}