<?php

namespace Proxies\__CG__\Sylius\Bundle\PromotionsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Coupon extends \Sylius\Bundle\PromotionsBundle\Entity\Coupon implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getUsageLimit()
    {
        $this->__load();
        return parent::getUsageLimit();
    }

    public function setUsageLimit($usageLimit)
    {
        $this->__load();
        return parent::setUsageLimit($usageLimit);
    }

    public function getUsed()
    {
        $this->__load();
        return parent::getUsed();
    }

    public function setUsed($used)
    {
        $this->__load();
        return parent::setUsed($used);
    }

    public function incrementUsed()
    {
        $this->__load();
        return parent::incrementUsed();
    }

    public function getPromotion()
    {
        $this->__load();
        return parent::getPromotion();
    }

    public function setPromotion(\Sylius\Bundle\PromotionsBundle\Model\PromotionInterface $promotion = NULL)
    {
        $this->__load();
        return parent::setPromotion($promotion);
    }

    public function getExpiresAt()
    {
        $this->__load();
        return parent::getExpiresAt();
    }

    public function setExpiresAt(\DateTime $expiresAt = NULL)
    {
        $this->__load();
        return parent::setExpiresAt($expiresAt);
    }

    public function isValid()
    {
        $this->__load();
        return parent::isValid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'code', 'usageLimit', 'used', 'expiresAt', 'id', 'promotion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}