<?php

namespace Proxies\__CG__\Sylius\Bundle\AssortmentBundle\Entity\Property;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultProductProperty extends \Sylius\Bundle\AssortmentBundle\Entity\Property\DefaultProductProperty implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getProduct()
    {
        $this->__load();
        return parent::getProduct();
    }

    public function setProduct(\Sylius\Bundle\AssortmentBundle\Model\ProductInterface $product = NULL)
    {
        $this->__load();
        return parent::setProduct($product);
    }

    public function getProperty()
    {
        $this->__load();
        return parent::getProperty();
    }

    public function setProperty(\Sylius\Bundle\AssortmentBundle\Model\Property\PropertyInterface $property)
    {
        $this->__load();
        return parent::setProperty($property);
    }

    public function getValue()
    {
        $this->__load();
        return parent::getValue();
    }

    public function setValue($value)
    {
        $this->__load();
        return parent::setValue($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getPresentation()
    {
        $this->__load();
        return parent::getPresentation();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getOptions()
    {
        $this->__load();
        return parent::getOptions();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'value', 'product', 'property', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}