<?php

namespace Proxies\__CG__\Sylius\Bundle\ShippingBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultShippingMethod extends \Sylius\Bundle\ShippingBundle\Entity\DefaultShippingMethod implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setCategory(\Sylius\Bundle\ShippingBundle\Model\ShippingCategoryInterface $category = NULL)
    {
        $this->__load();
        return parent::setCategory($category);
    }

    public function getCategoryRequirement()
    {
        $this->__load();
        return parent::getCategoryRequirement();
    }

    public function setCategoryRequirement($categoryRequirement)
    {
        $this->__load();
        return parent::setCategoryRequirement($categoryRequirement);
    }

    public function getCategoryRequirementLabel()
    {
        $this->__load();
        return parent::getCategoryRequirementLabel();
    }

    public function supports(\Sylius\Bundle\ShippingBundle\Model\ShippablesAwareInterface $shippablesAware)
    {
        $this->__load();
        return parent::supports($shippablesAware);
    }

    public function isEnabled()
    {
        $this->__load();
        return parent::isEnabled();
    }

    public function setEnabled($enabled)
    {
        $this->__load();
        return parent::setEnabled($enabled);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getCalculator()
    {
        $this->__load();
        return parent::getCalculator();
    }

    public function setCalculator($calculator)
    {
        $this->__load();
        return parent::setCalculator($calculator);
    }

    public function getConfiguration()
    {
        $this->__load();
        return parent::getConfiguration();
    }

    public function setConfiguration(array $configuration)
    {
        $this->__load();
        return parent::setConfiguration($configuration);
    }

    public function hasRules()
    {
        $this->__load();
        return parent::hasRules();
    }

    public function getRules()
    {
        $this->__load();
        return parent::getRules();
    }

    public function hasRule(\Sylius\Bundle\ShippingBundle\Model\RuleInterface $rule)
    {
        $this->__load();
        return parent::hasRule($rule);
    }

    public function addRule(\Sylius\Bundle\ShippingBundle\Model\RuleInterface $rule)
    {
        $this->__load();
        return parent::addRule($rule);
    }

    public function removeRule(\Sylius\Bundle\ShippingBundle\Model\RuleInterface $rule)
    {
        $this->__load();
        return parent::removeRule($rule);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'configuration', 'categoryRequirement', 'calculator', 'enabled', 'createdAt', 'updatedAt', 'category', 'id', 'rules');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}