<?php

namespace Proxies\__CG__\Sylius\Bundle\SalesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultOrderItem extends \Sylius\Bundle\SalesBundle\Entity\DefaultOrderItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getQuantity()
    {
        $this->__load();
        return parent::getQuantity();
    }

    public function setQuantity($quantity)
    {
        $this->__load();
        return parent::setQuantity($quantity);
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setOrder(\Sylius\Bundle\SalesBundle\Model\OrderInterface $order = NULL)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function getSellable()
    {
        $this->__load();
        return parent::getSellable();
    }

    public function setSellable(\Sylius\Bundle\SalesBundle\Model\SellableInterface $sellable)
    {
        $this->__load();
        return parent::setSellable($sellable);
    }

    public function getUnitPrice()
    {
        $this->__load();
        return parent::getUnitPrice();
    }

    public function setUnitPrice($unitPrice)
    {
        $this->__load();
        return parent::setUnitPrice($unitPrice);
    }

    public function getAdjustments()
    {
        $this->__load();
        return parent::getAdjustments();
    }

    public function addAdjustment(\Sylius\Bundle\SalesBundle\Model\AdjustmentInterface $adjustment)
    {
        $this->__load();
        return parent::addAdjustment($adjustment);
    }

    public function removeAdjustment(\Sylius\Bundle\SalesBundle\Model\AdjustmentInterface $adjustment)
    {
        $this->__load();
        return parent::removeAdjustment($adjustment);
    }

    public function hasAdjustment(\Sylius\Bundle\SalesBundle\Model\AdjustmentInterface $adjustment)
    {
        $this->__load();
        return parent::hasAdjustment($adjustment);
    }

    public function getAdjustmentsTotal()
    {
        $this->__load();
        return parent::getAdjustmentsTotal();
    }

    public function calculateAdjustmentsTotal()
    {
        $this->__load();
        return parent::calculateAdjustmentsTotal();
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function calculateTotal()
    {
        $this->__load();
        return parent::calculateTotal();
    }

    public function equals(\Sylius\Bundle\SalesBundle\Model\OrderItemInterface $orderItem)
    {
        $this->__load();
        return parent::equals($orderItem);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'quantity', 'unitPrice', 'adjustmentsTotal', 'total', 'order', 'sellable', 'id', 'adjustments');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}