<?php

namespace Proxies\__CG__\Sylius\Bundle\PaymentsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Payment extends \Sylius\Bundle\PaymentsBundle\Entity\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getMethod()
    {
        $this->__load();
        return parent::getMethod();
    }

    public function setMethod(\Sylius\Bundle\PaymentsBundle\Model\PaymentMethodInterface $method = NULL)
    {
        $this->__load();
        return parent::setMethod($method);
    }

    public function setSource(\Sylius\Bundle\PaymentsBundle\Model\PaymentSourceInterface $source = NULL)
    {
        $this->__load();
        return parent::setSource($source);
    }

    public function getSource()
    {
        $this->__load();
        return parent::getSource();
    }

    public function getCurrency()
    {
        $this->__load();
        return parent::getCurrency();
    }

    public function setCurrency($currency)
    {
        $this->__load();
        return parent::setCurrency($currency);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function addTransaction(\Sylius\Bundle\PaymentsBundle\Model\TransactionInterface $transaction)
    {
        $this->__load();
        return parent::addTransaction($transaction);
    }

    public function getTransactions()
    {
        $this->__load();
        return parent::getTransactions();
    }

    public function hasTransaction(\Sylius\Bundle\PaymentsBundle\Model\TransactionInterface $transaction)
    {
        $this->__load();
        return parent::hasTransaction($transaction);
    }

    public function getBalance()
    {
        $this->__load();
        return parent::getBalance();
    }

    public function removeTransaction(\Sylius\Bundle\PaymentsBundle\Model\TransactionInterface $transaction)
    {
        $this->__load();
        return parent::removeTransaction($transaction);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'currency', 'amount', 'createdAt', 'updatedAt', 'id', 'transactions', 'method', 'creditCard');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}