<?php

namespace Proxies\__CG__\Gecko\PigalleBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProductCollection extends \Gecko\PigalleBundle\Entity\ProductCollection implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getShortDescription()
    {
        $this->__load();
        return parent::getShortDescription();
    }

    public function setShortDescription($shortDescription)
    {
        $this->__load();
        return parent::setShortDescription($shortDescription);
    }

    public function hasImage(\Sylius\Bundle\CoreBundle\Model\ImageInterface $image)
    {
        $this->__load();
        return parent::hasImage($image);
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function addImage(\Sylius\Bundle\CoreBundle\Model\ImageInterface $image)
    {
        $this->__load();
        return parent::addImage($image);
    }

    public function removeImage(\Sylius\Bundle\CoreBundle\Model\ImageInterface $image)
    {
        $this->__load();
        return parent::removeImage($image);
    }

    public function getTaxons()
    {
        $this->__load();
        return parent::getTaxons();
    }

    public function setTaxons(\Doctrine\Common\Collections\Collection $taxons)
    {
        $this->__load();
        return parent::setTaxons($taxons);
    }

    public function hasOptions()
    {
        $this->__load();
        return parent::hasOptions();
    }

    public function getOptions()
    {
        $this->__load();
        return parent::getOptions();
    }

    public function setOptions(\Doctrine\Common\Collections\Collection $options)
    {
        $this->__load();
        return parent::setOptions($options);
    }

    public function addOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::addOption($option);
    }

    public function removeOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::removeOption($option);
    }

    public function hasOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::hasOption($option);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'slug', 'description', 'shortDescription', 'createdAt', 'updatedAt', 'images', 'taxons', 'options');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}