<?php

namespace Proxies\__CG__\Sylius\Bundle\AddressingBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Zone extends \Sylius\Bundle\AddressingBundle\Entity\Zone implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getMembers()
    {
        $this->__load();
        return parent::getMembers();
    }

    public function setMembers(\Doctrine\Common\Collections\Collection $members)
    {
        $this->__load();
        return parent::setMembers($members);
    }

    public function hasMembers()
    {
        $this->__load();
        return parent::hasMembers();
    }

    public function addMember(\Sylius\Bundle\AddressingBundle\Model\ZoneMemberInterface $member)
    {
        $this->__load();
        return parent::addMember($member);
    }

    public function removeMember(\Sylius\Bundle\AddressingBundle\Model\ZoneMemberInterface $member)
    {
        $this->__load();
        return parent::removeMember($member);
    }

    public function hasMember(\Sylius\Bundle\AddressingBundle\Model\ZoneMemberInterface $member)
    {
        $this->__load();
        return parent::hasMember($member);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'type', 'id', 'members');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}