<?php

namespace Proxies\__CG__\Sylius\Bundle\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Shipment extends \Sylius\Bundle\CoreBundle\Entity\Shipment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setOrder(\Sylius\Bundle\SalesBundle\Model\OrderInterface $order = NULL)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getMethod()
    {
        $this->__load();
        return parent::getMethod();
    }

    public function setMethod(\Sylius\Bundle\ShippingBundle\Model\ShippingMethodInterface $method)
    {
        $this->__load();
        return parent::setMethod($method);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function hasItem(\Sylius\Bundle\ShippingBundle\Model\ShipmentItemInterface $item)
    {
        $this->__load();
        return parent::hasItem($item);
    }

    public function addItem(\Sylius\Bundle\ShippingBundle\Model\ShipmentItemInterface $item)
    {
        $this->__load();
        return parent::addItem($item);
    }

    public function removeItem(\Sylius\Bundle\ShippingBundle\Model\ShipmentItemInterface $item)
    {
        $this->__load();
        return parent::removeItem($item);
    }

    public function getShippables()
    {
        $this->__load();
        return parent::getShippables();
    }

    public function getTracking()
    {
        $this->__load();
        return parent::getTracking();
    }

    public function setTracking($tracking)
    {
        $this->__load();
        return parent::setTracking($tracking);
    }

    public function isTracked()
    {
        $this->__load();
        return parent::isTracked();
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'state', 'tracking', 'createdAt', 'updatedAt', 'method', 'id', 'items', 'order');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}