<?php

namespace Proxies\__CG__\Sylius\Bundle\CoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \Sylius\Bundle\CoreBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getSku()
    {
        $this->__load();
        return parent::getSku();
    }

    public function setSku($sku)
    {
        $this->__load();
        return parent::setSku($sku);
    }

    public function getVariantSelectionMethod()
    {
        $this->__load();
        return parent::getVariantSelectionMethod();
    }

    public function setVariantSelectionMethod($variantSelectionMethod)
    {
        $this->__load();
        return parent::setVariantSelectionMethod($variantSelectionMethod);
    }

    public function isVariantSelectionMethodChoice()
    {
        $this->__load();
        return parent::isVariantSelectionMethodChoice();
    }

    public function getVariantSelectionMethodLabel()
    {
        $this->__load();
        return parent::getVariantSelectionMethodLabel();
    }

    public function getTaxons()
    {
        $this->__load();
        return parent::getTaxons();
    }

    public function setTaxons(\Doctrine\Common\Collections\Collection $taxons)
    {
        $this->__load();
        return parent::setTaxons($taxons);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function setIsFeatured($isFeatured)
    {
        $this->__load();
        return parent::setIsFeatured($isFeatured);
    }

    public function getIsFeatured()
    {
        $this->__load();
        return parent::getIsFeatured();
    }

    public function isFeatured()
    {
        $this->__load();
        return parent::isFeatured();
    }

    public function getPriceWithoutDiscount()
    {
        $this->__load();
        return parent::getPriceWithoutDiscount();
    }

    public function setPriceWithoutDiscount($price)
    {
        $this->__load();
        return parent::setPriceWithoutDiscount($price);
    }

    public function isOffer()
    {
        $this->__load();
        return parent::isOffer();
    }

    public function getShortDescription()
    {
        $this->__load();
        return parent::getShortDescription();
    }

    public function setShortDescription($shortDescription)
    {
        $this->__load();
        return parent::setShortDescription($shortDescription);
    }

    public function getTaxCategory()
    {
        $this->__load();
        return parent::getTaxCategory();
    }

    public function setTaxCategory(\Sylius\Bundle\TaxationBundle\Model\TaxCategoryInterface $category = NULL)
    {
        $this->__load();
        return parent::setTaxCategory($category);
    }

    public function getShippingCategory()
    {
        $this->__load();
        return parent::getShippingCategory();
    }

    public function setShippingCategory(\Sylius\Bundle\ShippingBundle\Model\ShippingCategoryInterface $category = NULL)
    {
        $this->__load();
        return parent::setShippingCategory($category);
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function isAvailable()
    {
        $this->__load();
        return parent::isAvailable();
    }

    public function getAvailableOn()
    {
        $this->__load();
        return parent::getAvailableOn();
    }

    public function setAvailableOn(\DateTime $availableOn)
    {
        $this->__load();
        return parent::setAvailableOn($availableOn);
    }

    public function getMasterVariant()
    {
        $this->__load();
        return parent::getMasterVariant();
    }

    public function setMasterVariant(\Sylius\Bundle\AssortmentBundle\Model\Variant\VariantInterface $masterVariant)
    {
        $this->__load();
        return parent::setMasterVariant($masterVariant);
    }

    public function hasVariants()
    {
        $this->__load();
        return parent::hasVariants();
    }

    public function getVariants()
    {
        $this->__load();
        return parent::getVariants();
    }

    public function getAvailableVariants()
    {
        $this->__load();
        return parent::getAvailableVariants();
    }

    public function setVariants(\Doctrine\Common\Collections\Collection $variants)
    {
        $this->__load();
        return parent::setVariants($variants);
    }

    public function addVariant(\Sylius\Bundle\AssortmentBundle\Model\Variant\VariantInterface $variant)
    {
        $this->__load();
        return parent::addVariant($variant);
    }

    public function removeVariant(\Sylius\Bundle\AssortmentBundle\Model\Variant\VariantInterface $variant)
    {
        $this->__load();
        return parent::removeVariant($variant);
    }

    public function hasVariant(\Sylius\Bundle\AssortmentBundle\Model\Variant\VariantInterface $variant)
    {
        $this->__load();
        return parent::hasVariant($variant);
    }

    public function hasOptions()
    {
        $this->__load();
        return parent::hasOptions();
    }

    public function getOptions()
    {
        $this->__load();
        return parent::getOptions();
    }

    public function setOptions(\Doctrine\Common\Collections\Collection $options)
    {
        $this->__load();
        return parent::setOptions($options);
    }

    public function addOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::addOption($option);
    }

    public function removeOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::removeOption($option);
    }

    public function hasOption(\Sylius\Bundle\AssortmentBundle\Model\Option\OptionInterface $option)
    {
        $this->__load();
        return parent::hasOption($option);
    }

    public function getProperties()
    {
        $this->__load();
        return parent::getProperties();
    }

    public function setProperties(\Doctrine\Common\Collections\Collection $properties)
    {
        $this->__load();
        return parent::setProperties($properties);
    }

    public function addProperty(\Sylius\Bundle\AssortmentBundle\Model\Property\ProductPropertyInterface $property)
    {
        $this->__load();
        return parent::addProperty($property);
    }

    public function removeProperty(\Sylius\Bundle\AssortmentBundle\Model\Property\ProductPropertyInterface $property)
    {
        $this->__load();
        return parent::removeProperty($property);
    }

    public function hasProperty(\Sylius\Bundle\AssortmentBundle\Model\Property\ProductPropertyInterface $property)
    {
        $this->__load();
        return parent::hasProperty($property);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getMetaKeywords()
    {
        $this->__load();
        return parent::getMetaKeywords();
    }

    public function setMetaKeywords($metaKeywords)
    {
        $this->__load();
        return parent::setMetaKeywords($metaKeywords);
    }

    public function getMetaDescription()
    {
        $this->__load();
        return parent::getMetaDescription();
    }

    public function setMetaDescription($metaDescription)
    {
        $this->__load();
        return parent::setMetaDescription($metaDescription);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getUpdatedAt()
    {
        $this->__load();
        return parent::getUpdatedAt();
    }

    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->__load();
        return parent::setUpdatedAt($updatedAt);
    }

    public function isDeleted()
    {
        $this->__load();
        return parent::isDeleted();
    }

    public function getDeletedAt()
    {
        $this->__load();
        return parent::getDeletedAt();
    }

    public function setDeletedAt(\DateTime $deletedAt)
    {
        $this->__load();
        return parent::setDeletedAt($deletedAt);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'slug', 'description', 'createdAt', 'updatedAt', 'deletedAt', 'options', 'shortDescription', 'isFeatured', 'priceWithoutDiscount', 'variantSelectionMethod', 'id', 'variants', 'properties', 'taxCategory', 'taxons');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}